name: flying_horse
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  get_storage: 2.1.1
  google_fonts: ^6.2.1
  connectivity_plus: ^6.0.1
  google_maps_flutter: ^2.7.0
  dotted_line: ^3.2.2
  syncfusion_flutter_datepicker: ^26.2.7
  csc_picker: ^0.2.7
  flutter_typeahead: ^5.2.0
  url_launcher: ^6.3.0
  flutter: 
    sdk: flutter
  intl: ^0.19.0
  field_suggestion: ^0.2.5

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

